system:
  socket: true
  port: 5100
  frontPort: 5108
  colors: true
  forkable: true
  processName: starter-kit
  argParser: true
  allowChildOutput: true
  beep: true
gulp:
  mainTask: init
  socket: true
  tasks:
    scss:
      before: imdone
      after: exit
      name: styles.css
      runOnStart: true
      concat: true
      dest: ./out
      paths: 
        - ./*.scss
      watch: true  
    jadeify:
      before: imdone
      after: imdone
      concat: false
      when: 'some condition'
      watch: true
      runOnStart: true
      dest: ./out
      paths: 
        - ./*.jade

processes: # default bin = node
  webpack:
    enable: false
    runOnStart: true
    socket: true
    bin: webpack
    node_modules: false
    fileTypes:
      - js
      - json
    mode: node
    entry: ./src/webpack-entry.js
    output: './out'
    filename: '[name].js'
    resolve:
      modulesDirectories:
        - node_modules
      ext:
        - js
        - json  
    directorys:
      - ./src/components
    loaders:
      javascript:
        test: js
        include: $dir/src
        loader: babel
        config:
          presets:
            - es2015
            - stage-0
          plugins: 
            - transform-es2015-modules-commonjs
            - transform-decorators-legacy
            - transform-class-properties

    vendors:
      - vue
      - mobx

    plugins:
      - OccurrenceOrderPlugin
  testing:
    runOnStart: true
    enable: true
    socket: false
    watch: true
    use: mocha
    assertion: chai
    script: ./tests